field: 8a506770-a48f-4247-a45f-7c487a68e5c8 # Content Main
fieldLayouts:
  81dff9ea-adbd-4102-8907-37b63bf25801:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 0005f40e-a30f-4270-b9a3-afa72589f5d3 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cae4242b-2044-4205-8beb-2f8e6d1377f4
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a6d56568-c9d1-4c56-a71f-ba21a451f3f8 # Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b17226a1-d9b7-4f9f-825b-d84f7cff1c26
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c3255379-fc6a-41d8-9b16-75e971ae675d # Promise
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5b2bd5f2-9b40-4b90-b95e-513e6285bba0
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d4bedb3c-89a8-4e11-a6c3-47cffb09b6da # Cta Button
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3cb86216-9403-4d06-af74-22bc87cc9802
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: e6f0081a-95d5-4ca9-b6af-b1f22da292d6
        userCondition: null
fields:
  0005f40e-a30f-4270-b9a3-afa72589f5d3: # Heading
    columnSuffix: xpdboivz
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: null
    name: Heading
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  a6d56568-c9d1-4c56-a71f-ba21a451f3f8: # Text
    columnSuffix: dgfejhme
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: null
    name: Text
    searchable: false
    settings:
      availableTransforms: ''
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: null
      removeEmptyTags: false
      removeInlineStyles: false
      removeNbsp: false
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  c3255379-fc6a-41d8-9b16-75e971ae675d: # Promise
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: promise
    instructions: null
    name: Promise
    searchable: false
    settings:
      blockTypeFields: 0
      changedFieldIndicator: 1770221859
      columns:
        __assoc__:
          -
            - 151e9d65-b232-4825-aea9-d62cd0476eeb # Promise Heading
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - a6f69c50-e0a6-4c9b-9f96-c4ab15c46a7d # Logo
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_10_promise}}'
      fieldLayout: table
      maxRows: 3
      minRows: null
      propagationKeyFormat: null
      propagationMethod: all
      selectionLabel: null
      staticField: null
    translationKeyFormat: null
    translationMethod: none
    type: verbb\supertable\fields\SuperTableField
  d4bedb3c-89a8-4e11-a6c3-47cffb09b6da: # Cta Button
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: ctaButton
    instructions: null
    name: 'Cta Button'
    searchable: false
    settings:
      allowSelfRelations: false
      branchLimit: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 1
      minRelations: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Entry
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\entries\EntryCondition
      selectionLabel: null
      showSiteMenu: true
      sources:
        - 'section:c817bba6-aae6-4a1d-81e4-a3a72b244306' # Buttons
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
handle: promisePanel
name: 'Promise Panel'
sortOrder: 7
