field: 8a506770-a48f-4247-a45f-7c487a68e5c8 # Content Main
fieldLayouts:
  242b0eec-88f8-47ee-846c-ed8ed7d78a38:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 19181c1b-be03-4fa3-84af-af5afdafd089 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 94ad66b4-0104-4bf3-9980-60d4bb3d0148
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 45e70cb5-2298-4e36-9b1b-27626b1427bb # Testimonials
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 38846c7a-f0bc-4267-88a5-c79a80a8e43f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 105e63a9-48d6-4c82-962f-7456bbb10d61
        userCondition: null
fields:
  45e70cb5-2298-4e36-9b1b-27626b1427bb: # Testimonials
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: testimonials
    instructions: null
    name: Testimonials
    searchable: false
    settings:
      allowSelfRelations: false
      branchLimit: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: null
      minRelations: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Entry
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\entries\EntryCondition
      selectionLabel: null
      showSiteMenu: true
      sources:
        - 'section:40d026ad-356b-4c89-89a4-1018f59e3cdb' # Testimonials
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  19181c1b-be03-4fa3-84af-af5afdafd089: # Heading
    columnSuffix: wydfwlfx
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: null
    name: Heading
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: testimonialscarousel
name: testimonialsCarousel
sortOrder: 3
