fieldLayouts:
  90ff02a9-2f32-4bc6-bf44-00bc2d5d3015:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 6c05fbc6-e47d-4aa6-882a-3dfdec04a190
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1450cb22-ba36-4da2-8ab4-c4d8b7c47709 # Button Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f16359c1-37b8-405f-aad4-714ed5a7e0e0
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b7cae76a-588f-4f19-8628-22e3d6e18b63 # Button Url
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 346f74a7-0251-4a71-9f38-704e8a0000dc
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 9264fa67-a5f0-429a-bfdc-a4244d847a30
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: c817bba6-aae6-4a1d-81e4-a3a72b244306 # Buttons
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
