fieldLayouts:
  7ce7b929-28ec-4bd7-a7ee-5b720e50f94c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 7e927578-c1fc-402c-9e01-f72960e64d18
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 2689ce55-4e16-4d89-9b26-4bd297a947aa
        userCondition: null
fs: images
handle: images
name: Images
sortOrder: 1
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
