changedFieldIndicator: 820134178
field: b896b734-709a-41bc-8cc8-598231afb85d # LinkCta
fieldLayouts:
  0530ace7-89fa-4ae2-8627-828649189ac3:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: e09be07d-ad22-4749-9553-21a2a415a998 # Link Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9ac62d9a-72d5-4f07-8a43-0e53ab20f3bb
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: fc364292-deda-4f37-bf55-2c1dd07b295c # Link Url
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5ee27020-b598-4cb6-aeb4-f524be9e68f9
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8aaf6ff5-f2f0-4547-8e05-b3eadc9ab336 # External
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 961670bc-bed4-4946-9b53-3a388cb6826a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 1e794d2b-fb85-4465-a9e1-56d770ae8ee3
        userCondition: null
fields:
  8aaf6ff5-f2f0-4547-8e05-b3eadc9ab336: # External
    columnSuffix: snbouzan
    contentColumnType: boolean
    fieldGroup: null
    handle: external
    instructions: null
    name: External
    searchable: false
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  e09be07d-ad22-4749-9553-21a2a415a998: # Link Text
    columnSuffix: ldbfynvk
    contentColumnType: text
    fieldGroup: null
    handle: linkText
    instructions: null
    name: 'Link Text'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  fc364292-deda-4f37-bf55-2c1dd07b295c: # Link Url
    columnSuffix: uatumtxk
    contentColumnType: string(255)
    fieldGroup: null
    handle: linkUrl
    instructions: null
    name: 'Link Url'
    searchable: false
    settings:
      maxLength: 255
      types:
        - url
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Url
