changedFieldIndicator: 951511082
field: 8a40c4ab-f2c9-4218-83bb-14ad32f63f2d # LinkCta
fieldLayouts:
  ed3d5dc7-2cc2-44f5-a4ee-4809f73ec620:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: db6039ae-01bb-4a72-8948-e4237047a910 # Link Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7afc1a47-6c33-4b36-bd95-d04a4cc8e5d1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b4b049e5-bfe5-4504-a5cf-2fbd16b0dd47 # LinkUrl
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 39336ed1-ceea-4bdc-8998-42a5b17fa51d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d71035cf-726c-4aa8-b2a7-6589c0a5f0b0 # External
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 292e6c2f-4dbc-47a7-bc22-73871d935333
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 2af751eb-42d1-4c98-9932-3387025ccd79
        userCondition: null
fields:
  b4b049e5-bfe5-4504-a5cf-2fbd16b0dd47: # LinkUrl
    columnSuffix: ykrwagdd
    contentColumnType: string(255)
    fieldGroup: null
    handle: linkUrl
    instructions: null
    name: LinkUrl
    searchable: false
    settings:
      maxLength: 255
      types:
        - url
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Url
  d71035cf-726c-4aa8-b2a7-6589c0a5f0b0: # External
    columnSuffix: llnvblnu
    contentColumnType: boolean
    fieldGroup: null
    handle: external
    instructions: null
    name: External
    searchable: false
    settings:
      default: false
      offLabel: Internal
      onLabel: External
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  db6039ae-01bb-4a72-8948-e4237047a910: # Link Text
    columnSuffix: odjfujem
    contentColumnType: text
    fieldGroup: null
    handle: linkText
    instructions: null
    name: 'Link Text'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
