defaultPlacement: end
enableVersioning: true
handle: buttons
name: Buttons
propagationMethod: all
siteSettings:
  2f6f7a07-cfba-4216-afc8-3caffb35601f: # SBS Cladding
    enabledByDefault: true
    hasUrls: true
    template: buttons/_entry
    uriFormat: 'buttons/{slug}'
type: channel
