defaultPlacement: end
enableVersioning: true
handle: testimonials
name: Testimonials
propagationMethod: all
siteSettings:
  2f6f7a07-cfba-4216-afc8-3caffb35601f: # SBS Cladding
    enabledByDefault: true
    hasUrls: true
    template: testimonials/_entry
    uriFormat: 'testimonials/{slug}'
type: channel
